### ISSUE TITLE
My server in blacklist

### ISSUE THREAD

**Issue by ZerxXxes** [logzilla/extras#1]
Hello, could you please explain on what grounds my server IP 193.11.114.43 is placed in this blacklist? Its a NTP-server and have nothing to do with WannaCry ransomware.

**Comment by logzilla** [comment]
Hi,
The blacklist is pulled from AlienVault's [Open Threat Exchange](otx.alienvault.com), so you will want to contact them and make the request. We have no control over it. (I'm happy to remove it from the example page we wrote though).

**Comment by ZerxXxes** [comment]
Ok, thank you. I will contact AlienVault.
