### ISSUE TITLE
Can't see rules

### ISSUE THREAD

**Issue by mmiat** [logzilla/extras#5]
I've create some rules, added them, and they appear when I run "logzilla rules list"
but none of them appears in LogZilla Web interface
what can I check?

**Comment by tomdamonlz** [comment]
Rules don't display in the UI. What is the output of 'logzilla rules list'? I can give you some pointers on how to display the info in dashboards and widgets once I know which rules you are using.

**Comment by mmiat** [comment]
I've tried with
https://github.com/logzilla/extras/blob/master/rules.d/untested/Linux/900-dhcpd-device-types.json
and
http://demo.logzilla.net/help/data_transformation/user_tags

my final goal is to divide clients and servers in 2 or more categories

**Comment by tomdamonlz** [comment]
If events have come in that match that rule, you should see the user tag as an option in the Field drop down when you edit a widget.

**Comment by mmiat** [comment]
ok tks, later I'll try again
but for my goal maybe I'm using wrong strategy: I've many clients and I want to divide them in "categories" and then create widget using categories, because in this way it's easier and faster to select them, is it possible?
thanks

**Comment by tomdamonlz** [comment]
You can use the Host filter in widgets for this, or create user tags based on hosts.
